### ISSUE TITLE
Docker部署

### ISSUE THREAD

**Issue by whoopscs** [ikxin/kms-tools#24]
**描述你想要的解决方案**

一个不错的项目，希望增加docker镜像部署

**Comment by tetepay** [comment]
如何使用Cloudflare部署

**Comment by ikxin** [comment]
> **描述你想要的解决方案**
> 
> 一个不错的项目，希望增加docker镜像部署

现在已经有了 Docker 镜像，但是我不确定大陆网络环境可以正常拉去，如有问题欢迎继续反馈

```bash
docker pull ikxin/kms-tools
```

**Comment by ikxin** [comment]
> 如何使用Cloudflare部署

可以 fork 本仓库到你的账号，然后在 Cloudflare Pages 使用 Github 导入项目

详见：https://developers.cloudflare.com/pages/get-started/git-integration/

**Comment by eniyiweb** [comment]
Unable to start docker.

```
Bun v1.1.27 (Linux arm64)

18696 |   module.exports = [

18697 |   module.exports = [

18698 |   module.exports = [

18699 |   module.exports = [

18700 |   module.exports = [

18701 |   module.exports = [

                                        ^

error: Failed to connect

 errno: 103

  code: "ECONNREFUSED"

      at createConnection (/$bunfs/root/kms-tools:18701:33)

      at module code (/$bunfs/root/kms-tools:34688:57)
```

Docker Compose:
```

services:
  kms-tools:
    build: .
    ports:
      - 3000:3000
    restart: unless-stopped
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'kmstool'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'otherpassword'
    ports:
      - '3306:3306'
    volumes:
      - /var/www/vhosts/eniyiweb.net/lisans.eniyiweb.net/db:/var/lib/mysql

volumes:
  my-db:

```
