### ISSUE TITLE
Unable to start docker

### ISSUE THREAD

**Issue by ikxin** [ikxin/kms-tools#27]
Unable to start docker.

```
Bun v1.1.27 (Linux arm64)

18696 |   module.exports = [

18697 |   module.exports = [

18698 |   module.exports = [

18699 |   module.exports = [

18700 |   module.exports = [

18701 |   module.exports = [

                                        ^

error: Failed to connect

 errno: 103

  code: "ECONNREFUSED"

      at createConnection (/$bunfs/root/kms-tools:18701:33)

      at module code (/$bunfs/root/kms-tools:34688:57)
```

Docker Compose:
```

services:
  kms-tools:
    build: .
    ports:
      - 3000:3000
    restart: unless-stopped
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'kmstool'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'otherpassword'
    ports:
      - '3306:3306'
    volumes:
      - /var/www/vhosts/eniyiweb.net/lisans.eniyiweb.net/db:/var/lib/mysql

volumes:
  my-db:

```

_Originally posted by @eniyiweb in https://github.com/ikxin/kms-tools/issues/24#issuecomment-2345761118_
